#export jobid8='MCntuples_25March'
#export jobid8='MCntuples_otherCh2'
#export jobid8='MCntuples_14April'
#export jobid8='MCntuples_13May'
export jobid8='newNtuple_3June'
export jobidmt='MCntuples_8April'
