# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'
require 'pathname'

$jobid = ENV['jobid']
$blind = ENV['blind']

# Figure out what run period we are in
$period = '13TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#
samples = Hash[
               "ttbar" => get_sample_names('TT'),
               "singlet" => get_sample_names('T_t'),
               "singletbar" => get_sample_names('Tbar_t'), 
               "wjets" => get_sample_names('JetsToLNu'),
               "wwjets" => get_sample_names('WW_'),
               "wzjets" => get_sample_names('WZ_'),
               "zzjets" => get_sample_names('ZZ_'),
               "zjets" => get_sample_names('JetsToLL_M-50'),
               "zjets_skimmedLL" => get_sample_names('jets_M50_skimmedLL'),
               "zjets_skimmedTT" => get_sample_names('jets_M50_skimmedTT'),
               "diboson" =>get_sample_names('WWTo')+get_sample_names('WZTo')+get_sample_names('ZZTo'),
               "extra" => Array['T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola','Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola','Tbar_t-channel','T_t-channel'],
               "ewk" => Array['Zjets_M50', 
                              'WWJetsTo2L2Nu_TuneZ2_8TeV',
                              'TTJets_FullLeptMGDecays_8TeV-madgraph-tauola','TTJets_SemiLeptMGDecays_8TeV-madgraph-tauola'], 
               # Maria's version
               "signalMCgg" => get_sample_names('GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8'),
               "signalMCvbf" => get_sample_names('vbfHiggsToETau'),
               "signalMCMuTaugg" => get_sample_names('GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8'),
               "signalMCMuTauvbf" => get_sample_names('VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8'),
               "ggHiggsTo2Taus" => get_sample_names('GluGluToHToTauTau_M-125_8TeV-powheg-pythia6'),
               "vbfHiggsTo2Taus" => get_sample_names('VBF_HToTauTau_M-125_8TeV-powheg-pythia6'),
               "Zembedded" => get_sample_names('ZetauEmbedded'),
               "dataSingleE" => get_sample_names('data_SingleElectron_Run2016'),
               "dataSingleM" => get_sample_names('data_SingleMuon_Run2016')
               
]



# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end
def get_plotter_results(analyzer)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
end

$mmefrfit_dir = "results/#{$jobid}/mmefakerate_fits"
directory $mmefrfit_dir
$mmefr_analyzer = "MMEAnalyzer"

$fr_binning2d = "'0,10,15,20,25,30,40,50,70,100,150,200 0,1.5,2.5'"
#$fr_binning2d = "'10,20,30,40,50,70,150,200 0,1.5,2.5'"

pol0 = "const"
pol0_vars = "const[ 0.5, 0, 1]"
pol1 = "p0+p1*x"
pol1_vars = "p0[ 0.5, 0, 1], p1[ 0.01, -0.1, 0.1]"
pol2 = "p0+p1*x+p2*x*x"
pol2_vars = "p0[ 0.01, 0, 1], p1[ 0.001, -1, 1], p2[ 0.005, 0, 1]"

erf = "scale*TMath::Erf((x-shift)*steep)+offset"
erf_vars =  "scale[0.1, 0, 10],shift[1., 0.8, 1.2],steep[100.], offset[1e-2, 0, 0.5]"


mme2dfr_fits   = Hash.new
mme2dfr_fits["e_os_eSuperLoose_eTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSuperLoose_eVTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSSuperLoose_eVTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSSuperLoose_eTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSSuperLoose_eVTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
]
mme2dfr_fits["e_os_eVLoose_eTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM", "zjets", "ttbar"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eVLoose_eVTight_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM", "zjets", "ttbar"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "20 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]


mme2dfr_fits["e_os_eSSuperLoose_eTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSuperLoose_eVTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eSuperLoose_eTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]
mme2dfr_fits["e_os_eVLoose_eVTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
                                         ]

mme2dfr_fits["e_os_eVLoose_eTight_Met30_eAbsEta_vs_ePt"] = Hash[ 
                                          "samples" => Array["diboson",  "dataSingleM"],
                                          "analyzer" => $mmefr_analyzer,
                                        #"function" => exponential,
                                          #"variables" => exponential_vars,
                                          "function" => pol1, 
                                          "variables"=>pol1_vars, 
                                          #"rebin" => 1,
                                          "rebin" => $fr_binning2d,
                                          "range" => "10 200",
                                          "title" => "e p_{T} (GeV)",
                                          "min"=>"0",
                                        "max"=>"1"
]

##task :mmefits2d => []
##mme2dfr_fits.each do |fit, fit_info|
##  fit_configuration = fit.split("_")
##  sign = fit_configuration[1]
##  denom = fit_configuration[2]
##  num = fit_configuration[3]
##  #var = fit_configuration[4]+'_vs_'+fit_configuration[6]
##  var = fit_configuration[fit_configuration.length-3]+'_vs_'+fit_configuration[fit_configuration.length-1]
##  
##  subsample_inputs = []
##  fit_info['samples'].each do |sample|
##    subsample_inputs += samples[sample]
###    if sample=='diboson' or sample=='ttbar' then
###      subsample_inputs += samples[sample]
###    end
###    if sample=='dataSingleM' then
###      subsample_inputs += samples[sample]
###    end  
##  end
##  fit_output = $mmefrfit_dir + "/#{fit}.root"
##  subsamples_inputs_result_list = subsample_inputs.map{|x|  "results/#{$jobid}/#{fit_info['analyzer']}/#{x}.root"}
##  subsample_input_list = subsamples_inputs_result_list.join(" ")
##  $d=fit_configuration.length-1
##  #denom_path=Array[]
##  #num_path=Array[]
##  puts $d
##  if $d>6 then
##    puts fit_configuration
##    region = fit_configuration[4]
##    denom_path = Array[sign, denom,region,var].join("/")
##    num_path = Array[sign, num,region,var].join("/")
##    puts $d, num_path, denom_path
##
##    
##    corrected_file = fit_output.sub('.root', '.corrected_inputs.root')
##    #file corrected_file do |t|
##    sh "mkdir -p #{$mmefrfit_dir}"
##    sh "python  CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{corrected_file} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']}"
##    puts ""
##
##  else
##
##    puts fit_configuration
##    denom_path = Array[sign, denom,var].join("/")
##    num_path = Array[sign, num,var].join("/")
##    puts $d, num_path, denom_path
##
##    
##    corrected_file = fit_output.sub('.root', '.corrected_inputs.root')
##    #file corrected_file do |t|
##    sh "mkdir -p #{$mmefrfit_dir}"
##    sh "python  CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{corrected_file} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']}"
##    puts ""
##  
##  end
##
##  # Path to histograms in root files
##  #denom_path = Array[sign, denom,var].join("/")
##  #num_path = Array[sign, num, var].join("/")
##  
##  #corrected_file = fit_output.sub('.root', '.corrected_inputs.root')
##  #file corrected_file do |t|
##  #  sh "mkdir -p #{$mmefrfit_dir}"
##  #  sh "python CorrectFakeRateData.py --files #{subsample_input_list} --lumifiles inputs/#{$jobid}/*sum --outputfile #{t.name} --numerator '#{num_path}' --denom '#{denom_path}' --rebin #{fit_info['rebin']}"
##  #    puts ""
##  #end
##  
##  file fit_output => corrected_file do |t|
###    sh "fit_efficiency_chi2.py  #{fit_output} numerator denominator \'#{fit_info['function']}\' \'#{fit_info['variables']}\' #{corrected_file} --plot --xrange #{fit_info['range']} --xtitle \'#{fit_info['title']}\' --min \'#{fit_info['min']}\' --max \'#{fit_info['max']}\' --show-error "
##    puts ""
##  end
##  
##    
##  task :mmefits2d => fit_output
##  
##end
##

################################################################################
## Recipes to analyze the GG channel of the LFV HToMuTau analysis
##  targets:
##     mt
################################################################################

task :recoplots => get_analyzer_results("LFVHETauAnalyzer_13TeV.py", samples['dataSingleE']#samples['signalMCgg'] 
                                       )
task :muTrigger =>get_analyzer_results("TriggerAnalyzer.py",
                                        samples['signalMCMuTauvbf']+
                                        samples['signalMCMuTaugg']
                                       )
task :mueTrigger =>get_analyzer_results("TriggerAnalyzerME.py",
                                        samples['signalMCMuTauvbf']+
                                        samples['signalMCMuTaugg']
                                       )
task :fakeeet => get_analyzer_results("EETauAnalyzer.py",
                                      samples['dataSingleE'] +
                                      samples['zjets'] +  
                                      samples['wwjets']  + samples['zzjets'] + 
                                      samples['wzjets'] )
task :fakeeee => get_analyzer_results("EEEAnalyzer.py",
                                      samples['dataSingleE'] +
                                      samples['zjets'] +  
                                      samples['wwjets']  + samples['zzjets'] + 
                                      samples['wzjets'] )

task :fakemmt => get_analyzer_results("MMTauAnalyser.py",
                                      samples['dataSingleM'] +
                                      samples['zjets'] +  
                                      samples['wwjets']  + samples['zzjets'] + 
                                      samples['wzjets'] )

task :controlReReco => get_analyzer_results("MMEControl.py",
                                      samples['dataSingleM'] )
task :fakemmeData => get_analyzer_results("MMEAnalyzer.py",
                                      samples['dataSingleM'] )

task :fakemme => get_analyzer_results("MMEAnalyzer.py",
                                      samples['zjets'] +  
                                      #samples['ttbar'] + samples['singlet'] + samples['wjets']+
                                      samples['diboson']+
                                      samples['wwjets']+samples['wzjets']+samples['zzjets']
                                     )
task :fakeQCDmme => get_analyzer_results("MMEQCDAnalyzer.py",
                                      samples['dataSingleM'] +
                                      samples['zjets'] +  
                                      samples['wwjets']  + samples['zzjets'] + 
                                      samples['wzjets'] +
                                      samples['ttbar'] + samples['singlet'] + samples['wjets']
                                     )



task :genkin => get_analyzer_results("LFVHAnalyzeGEN.py", samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] )


task :genkinMuTau => get_analyzer_results("LFVHAnalyzeGENMuTau.py", samples['signalMCMuTaugg'] + samples['signalMCMuTauvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'])

task :genkinMuTauSIGNAL => get_analyzer_results("LFVHAnalyzeGENMuTau.py", samples['signalMCMuTaugg'])

task :genkinEMu => get_analyzer_results("LFVHAnalyzeGENEMu.py", samples['signalMCMuTaugg'] + samples['signalMCMuTauvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'])



task :recoplotsMVA => get_analyzer_results("LFVHETauAnalyzerMVA.py", samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] + 
                                                                     samples['dataSingleE'] 
                                           )
task :testMVA =>  get_analyzer_results("LFVHETauAnalyzerMVA.py", samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + 
                                       samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] + 
                                       samples['Zembedded']+
                                       samples['dataSingleE'] 
                                       )


task :recoplotsMVAeMtcut => get_analyzer_results("LFVHETauAnalyzerMVA_eMTCut.py", samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] + 
                                           samples['dataSingleE'] )


task :recoplotsMuTau => get_analyzer_results("LFVHMuTauAnalyzer.py", samples['signalMCMuTaugg'] + samples['signalMCMuTauvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] )

task :controlplots => get_analyzer_results("EEAnalyzer.py",samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] + samples['dataSingleE'])

task :controlplotsMVA => get_analyzer_results("EEAnalyzerMVA.py", #samples['signalMCvbf'] )#samples['zjets'])
                                              samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets'] + samples['wwjets'] + samples['wzjets'] + samples['zzjets'] + samples['zjets'] +  samples['Zembedded']+ samples['dataSingleE'])



task :fakeeVA => get_analyzer_results("EleFakeRateAnalyzerMVA.py", #samples['signalMCgg'] + samples['signalMCvbf'] + samples['ggHiggsTo2Taus'] + samples['vbfHiggsTo2Taus'] + samples['ttbar'] + samples['singlet'] + samples['singletbar'] + samples['wjets']  +   samples['Zembedded']+
                                         samples['zjets'] +
                                         samples['wwjets']  + samples['zzjets'] + 
                                         samples['wzjets']  +
                                         samples['dataSingleE']
                                         )


$etdir = "plots/#{$jobid}/LFVHETauAnalyzer/et/"
directory $etdir 
file  "#{$emtdir}/plot#{$period}.root" do |t|
  sh "echo $jobid"
  sh "python myNewPlotterReco.py" 
  
end


task :drawTauFakeRate => get_plotter_results("plotTauFakeRate.py")

##
## Make shapes
##
$shapedir = "plots/#{$jobid}/lfvet/"

#All shape files are made at the same time
## file "#{$shapedir}/.shapes_timestamp" => get_analyzer_results("LFVHETauAnalyzer.py", 
##                                      samples['signalMCgg'] + \
##                                      samples['signalMCvbf'] + \
##                                      samples['ggHiggsTo2Taus'] + \
##                                      samples['vbfHiggsTo2Taus'] + \
##                                      samples['ttbar'] + \
##                                      samples['singlet'] + \
##                                      samples['singletbar'] + \
##                                      samples['wjets'] + \
##                                      samples['wwjets'] + \
##                                      samples['wzjets'] + \
##                                      samples['zzjets'] + \
##                                      samples['zjets']) do |t|
##   sh "python plotRecoQuantitiesMVA.py"
##   sh "touch #{t.name}"
## end
file "#{$shapedir}/.shapes_timestamp" => [] do |t|
  sh "python plotRecoQuantitiesMVA.py"
end


## 
## Prepare datacards
## 
$limitdir = "limits/#{$jobid}/"
def prepare_limit(category)
  #input file does not matter since shape files are made all at once
  datacard = "#{$limitdir}/#{category}/126/datacard_et_#{category}.txt"
  file datacard => "#{$shapedir}/.shapes_timestamp" do |t|
    sh "./prepare_limit.sh #{category}"
  end
  return datacard
end

card_0_jet = prepare_limit('0')
card_1_jet = prepare_limit('1')
card_2_jet = prepare_limit('2')

#combine cards
cmb_card = "#{$limitdir}/cmb/126/datacard_et_cmb.txt"
file cmb_card => [card_0_jet, 
                  card_1_jet, 
                  card_2_jet] do |t|
  sh "mkdir -p #{$limitdir}/cmb/126"
  sh "hadd  -f #{$limitdir}/cmb/shapesETauHad.root #{$limitdir}/[0-9]/shapesETau$category?Jet.root"
  chdir("#{$limitdir}/cmb/126") do
    sh "rm -f shapesETauHad.root"
    sh "ln -s ../shapesETauHad.root"
    local_paths = t.prerequisites.map{|x| x.sub($limitdir,'../../')}
    local_name = File.basename(t.name)
    sh "combine_cards_with_names.sh #{ local_paths.join(' ')} > #{local_name}"
  end
end

#TODO combination!
task :shapes => [
   card_0_jet, 
   card_1_jet, 
   card_2_jet,
   cmb_card
]

## 
## Compute Limit
## 
def compute_limit(category)
  #input file does not matter since shape files are made all at once
  datacard = "#{$limitdir}/#{category}/126/datacard_et_#{category}.txt"
  timestamp = "#{$limitdir}/#{category}/.limit_timestamp"
  file timestamp => datacard do |t|
    sh "compute_limits.sh #{$limitdir}/#{category} 1 #{$blind}"
    sh "touch #{t.name}"
  end
  return timestamp  
end

limit_0_jet = compute_limit('0')
limit_1_jet = compute_limit('1')
limit_2_jet = compute_limit('2')
limit_c_jet = compute_limit('cmb')
#TODO combination!
task :limits => [
   limit_0_jet,
   limit_1_jet,
   limit_2_jet,
   limit_c_jet,
]

## 
## Compute Significance
## 
def compute_significance(category)
  #input file does not matter since shape files are made all at once
  datacard = "#{$limitdir}/#{category}/126/datacard_et_#{category}.txt"
  timestamp = "#{$limitdir}/#{category}/.significance_timestamp"
  file timestamp => datacard do |t|
    chdir("#{$limitdir}/#{category}") do
      dcard_name = File.basename(datacard)
      sh "compute_significance.sh 126 #{$blind} #{dcard_name}"
    end
    sh "touch #{t.name}"
  end
  return timestamp  
end

significance_0_jet = compute_significance('0')
significance_1_jet = compute_significance('1')
significance_2_jet = compute_significance('2')
significance_c_jet = compute_significance('cmb')
#TODO combination!
task :significance => [
   significance_0_jet,
   significance_1_jet,
   significance_2_jet,
#   significance_c_jet
]

